In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

In [ ]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
data.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
data.duplicated().sum()

33

In [ ]:
data=data.drop_duplicates()

In [ ]:
data.duplicated().sum()

0

In [ ]:
x=data.iloc[:,0:2].values

In [ ]:
y=data.iloc[:,-1].values

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [ ]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
x_train.shape

(293, 2)

In [ ]:
x_test.shape

(74, 2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [ ]:
x_train=sc.fit_transform(x_train)
x_train

array([[ 0.23103554,  0.24327798],
       [-0.42618207, -0.27913573],
       [ 1.73324722, -0.27913573],
       [ 0.88825315, -1.14982524],
       [ 0.13714731,  0.09816306],
       [-0.33229384, -0.77252645],
       [ 1.63935899, -0.88861839],
       [ 1.92102368, -0.65643452],
       [-1.27117614, -0.42425065],
       [ 0.79436492, -1.09177927],
       [ 0.79436492,  0.27230096],
       [-1.08339968, -1.58517   ],
       [ 0.23103554, -0.65643452],
       [-0.23840561,  0.09816306],
       [-0.14451738,  0.85276064],
       [ 2.01491191,  0.53350782],
       [ 0.79436492,  1.37517435],
       [-1.36506437, -1.20787121],
       [ 0.418812  , -0.13402081],
       [ 0.418812  , -0.16304379],
       [-0.33229384,  1.31712838],
       [-0.23840561,  0.79471467],
       [ 0.418812  ,  0.99787556],
       [ 1.07602961,  0.47546185],
       [-0.23840561,  0.27230096],
       [ 0.51270023,  1.72345015],
       [ 0.88825315,  1.08494451],
       [-0.80173499, -0.25011274],
       [-0.23840561,

In [ ]:
x_test=sc.transform(x_test)
x_test

array([[-0.70784676, -1.58517   ],
       [-0.5200703 ,  1.37517435],
       [ 0.23103554, -0.36620468],
       [ 1.82713545, -0.27913573],
       [-0.23840561,  0.53350782],
       [-0.5200703 ,  0.47546185],
       [ 0.04325908, -0.54034258],
       [ 0.13714731,  0.76569169],
       [ 1.82713545,  1.52028927],
       [-0.23840561, -0.88861839],
       [ 1.92102368,  0.91080661],
       [-0.05062915, -0.22108976],
       [ 0.23103554,  2.10074894],
       [-1.55284083,  0.53350782],
       [ 0.79436492, -0.30815871],
       [ 0.79436492,  0.35936992],
       [ 0.418812  ,  2.30390983],
       [ 1.54547076,  0.01109411],
       [-0.23840561,  0.15620903],
       [ 2.01491191, -1.17884822],
       [-0.14451738, -0.56936557],
       [-1.08339968, -1.14982524],
       [ 0.98214138,  2.07172596],
       [ 0.32492377,  0.50448483],
       [ 0.23103554,  0.06914008],
       [-1.17728791,  0.27230096],
       [ 1.07602961,  0.5625308 ],
       [ 2.01491191,  0.3883929 ],
       [ 0.418812  ,

In [ ]:
#finding k value
np.sqrt(x_train.shape[0])

17.11724276862369

In [ ]:
k=17

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=17)


In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
y_pred.shape

(74,)

In [ ]:
y_test.shape

(74,)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score (y_test,y_pred)


0.8918918918918919

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[41,  4],
       [ 4, 25]])