In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

In [ ]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
data.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
data.duplicated().sum()

33

In [ ]:
data=data.drop_duplicates()

In [ ]:
data.duplicated().sum()

0

In [ ]:
x=data.iloc[:,0:2].values

In [ ]:
y=data.iloc[:,-1].values

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [ ]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
x_train.shape

(293, 2)

In [ ]:
x_test.shape

(74, 2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [ ]:
xtrain.shape

NameError: name 'xtrain' is not defined

In [ ]:
x_test=sc.transform(x_test)
x_test

array([[ 0.96046655,  0.80157531],
       [ 0.20397005,  0.0974307 ],
       [ 2.00064925,  0.56686044],
       [ 1.81152512, -1.2521798 ],
       [-0.07971614,  0.03875199],
       [-1.49814709, -1.48689467],
       [ 0.96046655, -0.81208942],
       [ 1.81152512,  1.56439864],
       [ 2.00064925,  2.18052517],
       [-1.87639534, -0.48935647],
       [ 0.96046655,  1.91647095],
       [ 1.43327687,  1.03629018],
       [ 0.77134243,  0.15610942],
       [-0.55252646,  0.91893275],
       [-0.26884027, -0.2546416 ],
       [ 1.622401  ,  1.65241672],
       [-0.4579644 , -0.2546416 ],
       [-0.4579644 , -1.19350108],
       [-0.93077471,  0.5961998 ],
       [-1.02533678,  0.62553916],
       [-0.83621265, -0.63605327],
       [-0.55252646,  1.41770185],
       [-0.07971614,  0.30280621],
       [-1.30902297, -1.45755531],
       [-0.55252646,  1.50571992],
       [-1.02533678, -0.31332032],
       [-0.17427821,  2.20986453],
       [ 1.05502862,  0.15610942],
       [ 0.39309417,

In [ ]:
#finding k value
np.sqrt(x_train.shape[0])

17.11724276862369

In [ ]:
k=17

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=17)


In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [ ]:
y_pred=knn.predict(x_test)

In [ ]:
y_pred.shape

(74,)

In [ ]:
y_test.shape

(74,)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score (y_test,y_pred)


0.8513513513513513

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[38,  6],
       [ 5, 25]])